/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;

import dao.DAOFactory;
import dao.LivroDAO;
import dao.LivroDAOJDBC;
import java.awt.Component;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import modelo.Livro;
import modelo.Usuario;

/**
 *
 * @author Lídia Lis
 */

public class FrmAcervo extends javax.swing.JFrame {

    LivroDAO livroDAO = DAOFactory.criarLivroDAO();
    DefaultTableModel modelo = null;
   SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form frmAcervo
     */
    public FrmAcervo() {
        initComponents();
        modelo = (DefaultTableModel) tblAcervo.getModel();
        preencherTabela();
        atualizarTabela();
    }
    
    private void atualizarTabela(String campo, Object valor) {
    DefaultTableModel model = (DefaultTableModel) tblAcervo.getModel();
    model.setRowCount(0);

    LivroDAOJDBC dao = new LivroDAOJDBC();
    List<Livro> livros = dao.listarPorCampo(campo, valor);
        if (livros.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum livro encontrado com o filtro aplicado.");
        }

    for (Livro livro : livros) {
        model.addRow(new Object[]{
            livro.getId_livro(),
            livro.getId_doador().getNome(), // agora mostra o nome do doador
            livro.getTitulo(),
            livro.getAutor(),
            livro.getGenero(),
            livro.getData_doacao(),
            livro.getDisponivel()
        });
    }
    }
    private void atualizarTabela() {
    DefaultTableModel model = (DefaultTableModel) tblAcervo.getModel();
    model.setRowCount(0);

    LivroDAO dao = new LivroDAOJDBC();
    List<Livro> livros = dao.listar(); 

    for (Livro livro : livros) {
        model.addRow(new Object[]{
            livro.getId_livro(),
            livro.getId_doador().getNome(),
            livro.getTitulo(),
            livro.getAutor(),
            livro.getGenero(),
            livro.getData_doacao(),
            livro.getDisponivel()
        });
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ScrollLivro = new javax.swing.JScrollPane();
        tblAcervo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnInserir1 = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbDisponivel = new javax.swing.JComboBox<>();
        cbDoador = new javax.swing.JComboBox<>();
        cbGenero = new javax.swing.JComboBox<>();
        cbTitulo = new javax.swing.JComboBox<>();
        cbAutor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 244));

        ScrollLivro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ScrollLivro.setForeground(new java.awt.Color(255, 255, 204));

        tblAcervo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Livro", "Doador", "Titulo", "Autor", "Gênero", "Data Doação", "Disponivel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAcervo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblAcervoFocusGained(evt);
            }
        });
        ScrollLivro.setViewportView(tblAcervo);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Edita a linha selecionada.");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnInserir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/image-gallery.png"))); // NOI18N
        btnInserir1.setText("Inserir");
        btnInserir1.setToolTipText("Insere um novo livro.");
        btnInserir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserir1ActionPerformed(evt);
            }
        });

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/delete.png"))); // NOI18N
        btnApagar.setText("Apagar");
        btnApagar.setToolTipText("Apaga a linha selecionada.");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 244));

        cbDisponivel.setToolTipText("Selecione para realizar a busca.");
        cbDisponivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDisponivelActionPerformed(evt);
            }
        });

        cbDoador.setModel(new javax.swing.DefaultComboBoxModel(
            java.util.stream.IntStream.range(0, tblAcervo.getRowCount())
            .mapToObj(i -> tblAcervo.getValueAt(i, 1).toString())
            .toArray()
        )
    );
    cbDoador.setToolTipText("Selecione para realizar a busca.");
    cbDoador.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            cbDoadorFocusGained(evt);
        }
    });
    cbDoador.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbDoadorActionPerformed(evt);
        }
    });

    cbGenero.setToolTipText("Selecione para realizar a busca.");
    cbGenero.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusLost(java.awt.event.FocusEvent evt) {
            cbGeneroFocusLost(evt);
        }
    });
    cbGenero.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbGeneroActionPerformed(evt);
        }
    });

    cbTitulo.setToolTipText("Selecione para realizar a busca.");
    cbTitulo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbTituloActionPerformed(evt);
        }
    });

    cbAutor.setToolTipText("Selecione para realizar a busca.");
    cbAutor.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbAutorActionPerformed(evt);
        }
    });

    jLabel5.setText("  Titulo  ");
    jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));

    jLabel6.setText("  Autor  ");
    jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));

    jLabel1.setText("  Gênero  ");
    jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));

    jLabel7.setText("  Doador  ");
    jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));

    jLabel4.setText("   Disponivel   ");
    jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));

    jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/filter.png"))); // NOI18N
    jLabel14.setText("Filtro:");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(jLabel14)
            .addGap(28, 28, 28)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cbDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel7)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jLabel1))
                .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(44, 44, 44)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jLabel5))
                .addComponent(cbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(32, 32, 32)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel6)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(cbDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(jLabel4)))
            .addGap(95, 95, 95))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cbDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))))
            .addContainerGap(41, Short.MAX_VALUE))
    );

    btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/broom.png"))); // NOI18N
    btnLimpar.setText("Limpar");
    btnLimpar.setToolTipText("Limpa os filtros de busca.");
    btnLimpar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLimparActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(209, 209, 209)
            .addComponent(btnInserir1)
            .addGap(55, 55, 55)
            .addComponent(btnEditar)
            .addGap(47, 47, 47)
            .addComponent(btnApagar)
            .addGap(49, 49, 49)
            .addComponent(btnLimpar)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(90, 90, 90)
            .addComponent(ScrollLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(294, 294, 294)
                    .addComponent(jLabel3)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                    .addComponent(ScrollLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(43, 43, 43)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInserir1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29))))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblAcervoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblAcervoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tblAcervoFocusGained

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    int linhaSelecionada = tblAcervo.getSelectedRow();
    if (linhaSelecionada == -1) {
    JOptionPane.showMessageDialog(this, "Selecione uma linha para editar.");
    return;
    }

    int idLivro = (int) tblAcervo.getValueAt(linhaSelecionada, 0);
    DialogAcervo dialog = new DialogAcervo(this, true, idLivro);
    dialog.setVisible(true);

    atualizarTabela();
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnInserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserir1ActionPerformed
    DialogAcervo dialog = new DialogAcervo(this, true,null);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);

    atualizarTabela();

    }//GEN-LAST:event_btnInserir1ActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
    int linhaSelecionada = tblAcervo.getSelectedRow();

    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione a linha a ser apagada!", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirmacao = JOptionPane.showConfirmDialog(
        this,
        "Tem certeza que deseja apagar essa linha?",
        "Confirmar exclusão",
        JOptionPane.YES_NO_OPTION
    );

    if (confirmacao == JOptionPane.YES_OPTION) {
        int idLivro = (int) tblAcervo.getValueAt(linhaSelecionada, 0);

        try {
            // Usa a implementação correta do DAO
            LivroDAO dao = new LivroDAOJDBC();

            // Tenta apagar do banco
            int sucesso = dao.apagar(idLivro);

            if (sucesso > 0) {
                ((DefaultTableModel) tblAcervo.getModel()).removeRow(linhaSelecionada);
                JOptionPane.showMessageDialog(this, "Livro apagado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao apagar o livro!", "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao tentar apagar o livro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    //Tooltip
    cbGenero.setRenderer(new DefaultListCellRenderer() {
    @Override
    public Component getListCellRendererComponent(JList<?> list,
                                                  Object value,
                                                  int index,
                                                  boolean isSelected,
                                                  boolean cellHasFocus) {
        Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        if (c instanceof JComponent) {
            ((JComponent) c).setToolTipText(value.toString());
        }
        return c;
    }
    });

    }//GEN-LAST:event_btnApagarActionPerformed

    private void cbDisponivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDisponivelActionPerformed
    atualizarTabela("disponivel", cbDisponivel.getSelectedItem().toString());
    }//GEN-LAST:event_cbDisponivelActionPerformed

    private void cbAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAutorActionPerformed
    atualizarTabela("autor", cbAutor.getSelectedItem().toString());
    }//GEN-LAST:event_cbAutorActionPerformed

    private void cbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGeneroActionPerformed
atualizarTabela("genero", cbGenero.getSelectedItem().toString());
    }//GEN-LAST:event_cbGeneroActionPerformed

    private void cbTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTituloActionPerformed
    atualizarTabela("titulo", cbTitulo.getSelectedItem().toString());
    }//GEN-LAST:event_cbTituloActionPerformed

    private void cbDoadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbDoadorFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDoadorFocusGained

    private void cbDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDoadorActionPerformed
    atualizarTabela("doador", cbDoador.getSelectedItem().toString());
    }//GEN-LAST:event_cbDoadorActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
LivroDAO dao = new LivroDAOJDBC();

DefaultComboBoxModel<Usuario> modeloUsuarios = new DefaultComboBoxModel<>();
for (Livro l : dao.listar()) {
    Usuario u = l.getId_doador();
    boolean jaExiste = false;
    for (int i = 0; i < modeloUsuarios.getSize(); i++) {
        if (modeloUsuarios.getElementAt(i).getId_usuario() == u.getId_usuario()) {
            jaExiste = true;
            break;
        }
    }
    if (!jaExiste) {
        modeloUsuarios.addElement(u); // adiciona só se ainda não tiver
    }
}

cbDoador.setModel(modeloUsuarios);
//
DefaultComboBoxModel<String> modeloGenero = new DefaultComboBoxModel<>();

for (Livro l : dao.listar()) {
    String genero = l.getGenero();
    if (modeloGenero.getIndexOf(genero) == -1) { 
        modeloGenero.addElement(genero);
    }
}
cbGenero.setModel(modeloGenero);
//
DefaultComboBoxModel<String> modeloTitulo = new DefaultComboBoxModel<>();


for (Livro l : dao.listar()) {
    String titulo = l.getTitulo();
    if (modeloTitulo.getIndexOf(titulo) == -1) { 
        modeloTitulo.addElement(titulo);
    }
}
cbTitulo.setModel(modeloTitulo);
//
DefaultComboBoxModel<String> modeloAutor = new DefaultComboBoxModel<>();

for (Livro l : dao.listar()) {
    String autor = l.getAutor();
    if (modeloAutor.getIndexOf(autor) == -1) {
        modeloAutor.addElement(autor);
    }
}
cbAutor.setModel(modeloAutor);
//
DefaultComboBoxModel<String> modeloDisponivel = new DefaultComboBoxModel<>();

for (Livro l : dao.listar()) {
    String disp = l.getDisponivel() ? "Sim" : "Não";
    if (modeloDisponivel.getIndexOf(disp) == -1) {
        modeloDisponivel.addElement(disp); // só adiciona se não existir
    }
}
cbDisponivel.setModel(modeloDisponivel);

    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ajustarLarguraColunas(tblAcervo);
        tblAcervo.getColumnModel().getColumn(0).setPreferredWidth(60);   // Coluna ID
        tblAcervo.getColumnModel().getColumn(6).setPreferredWidth(60);  // Coluna Disponivel
        tblAcervo.getColumnModel().getColumn(5).setPreferredWidth(80);   // Coluna Data


    }//GEN-LAST:event_formWindowOpened

    private void cbGeneroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbGeneroFocusLost
                

    }//GEN-LAST:event_cbGeneroFocusLost

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    cbDoador.setSelectedIndex(0);      // ou valorInicialDoador se quiser
        cbGenero.setSelectedIndex(0);
        cbTitulo.setSelectedIndex(0);
        cbAutor.setSelectedIndex(0);
        cbDisponivel.setSelectedIndex(0);

        atualizarTabela();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */


     private void preencherTabela() {
        modelo.getDataVector().clear();
        try {
            for (Livro livro : livroDAO.listar()) {
                modelo.addRow(new Object[]{livro.getId_livro(),
                                           livro.getId_doador().getNome(),
                                           livro.getTitulo(),
                                           livro.getAutor(),
                                           livro.getGenero(),
                                           formato.format(livro.getData_doacao()),
                                           livro.getDisponivel()}
                               );
            }
        } catch (Exception e) {
            throw e;
        }
    }
    public void ajustarLarguraColunas(JTable table) {
    for (int col = 0; col < table.getColumnCount(); col++) {
        TableColumn column = table.getColumnModel().getColumn(col);
        int larguraMaxima = 0;

        for (int row = 0; row < table.getRowCount(); row++) {
            TableCellRenderer renderer = table.getCellRenderer(row, col);
            Component comp = table.prepareRenderer(renderer, row, col);
            larguraMaxima = Math.max(comp.getPreferredSize().width, larguraMaxima);
        }

        // Adiciona uma margem extra
        larguraMaxima += 10;
        column.setPreferredWidth(larguraMaxima);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAcervo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAcervo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollLivro;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnInserir1;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbAutor;
    private javax.swing.JComboBox<String> cbDisponivel;
    private javax.swing.JComboBox<Usuario> cbDoador;
    private javax.swing.JComboBox<String> cbGenero;
    private javax.swing.JComboBox<String> cbTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTable tblAcervo;
    // End of variables declaration//GEN-END:variables
}
